# Generated by Django 4.0 on 2021-12-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position_salary', models.FloatField()),
            ],
            options={
                'verbose_name': 'Должность',
            },
        ),
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('bar_revenue', models.FloatField()),
                ('game_zone_revenue', models.FloatField()),
                ('vr_revenue', models.FloatField()),
                ('hall_cleaning', models.BooleanField(default=True)),
                ('hall_admin_discipline', models.BooleanField(default=True)),
                ('cach_admin_discipline', models.BooleanField(default=True)),
                ('shortage', models.FloatField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('cash_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_admin', to='auth.user')),
                ('hall_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall_admin', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('birth_date', models.DateField(null=True, verbose_name='Дата рождения')),
                ('employment_date', models.DateField(null=True, verbose_name='Дата трудоустройства')),
                ('attestation', models.BooleanField(default=False)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='salary.position')),
            ],
        ),
    ]
