# Generated by Django 4.0 on 2021-12-28 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=60)),
                ('position_salary', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(unique=True, verbose_name='Дата смены')),
                ('bar_revenue', models.FloatField(verbose_name='Выручка по бару')),
                ('game_zone_revenue', models.FloatField(verbose_name='Выручка игровой зоны')),
                ('vr_revenue', models.FloatField(default=0.0, verbose_name='Выручка VR')),
                ('hall_cleaning', models.BooleanField(default=False, verbose_name='Наведение порядка')),
                ('hall_admin_discipline', models.BooleanField(default=True, verbose_name='Сюблюдение дисциплины Админ зала')),
                ('cash_admin_discipline', models.BooleanField(default=True, verbose_name='Сюблюдение дисциплины Админ кассы')),
                ('shortage', models.FloatField(default=0, verbose_name='Недостача')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='URL')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверено')),
                ('cash_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_admin', to='auth.user')),
                ('hall_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall_admin', to='auth.user')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('birth_date', models.DateField(null=True, verbose_name='Дата рождения')),
                ('employment_date', models.DateField(default=0, verbose_name='Дата трудоустройства')),
                ('attestation', models.BooleanField(default=False, verbose_name='Прохождение аттестации')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='salary.position')),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
            },
        ),
    ]
