# Generated by Django 4.0 on 2021-12-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
    ]
