# Generated by Django 4.0 on 2021-12-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='workingshift',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AlterField(
            model_name='position',
            name='position_salary',
            field=models.FloatField(null=True),
        ),
    ]
