# Generated by Django 4.0 on 2021-12-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_rename_positions_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingshift',
            old_name='discipline',
            new_name='cach_admin_discipline',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='login',
        ),
        migrations.AddField(
            model_name='workingshift',
            name='hall_admin_discipline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workingshift',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
