# Generated by Django 4.0 on 2021-12-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_rename_discipline_workingshift_cach_admin_discipline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='position',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='workingshift',
            name='cash_admin_id',
        ),
        migrations.RemoveField(
            model_name='workingshift',
            name='hall_admin_id',
        ),
    ]
