# Generated by Django 4.0.3 on 2022-05-02 13:03

from django.db import migrations, models

from salary.models import WorkingShift


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_workingshift_summary_revenue'),
    ]

    def set_summary_revenue(*args):
        for workshift in WorkingShift.objects.all():
            workshift.save()

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='game_zone_subtotal',
            field=models.FloatField(default=0.0, verbose_name='Подытог по игоровой зоне'),
        ),
        migrations.RunPython(set_summary_revenue),
    ]
