# Generated by Django 4.0 on 2021-12-11 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('salary', '0005_remove_employee_id_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='hall_admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
