# Generated by Django 4.0.3 on 2022-05-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_workingshift_game_zone_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Адрес эл. почты подтвержден'),
        ),
    ]
