# Generated by Django 4.0 on 2021-12-11 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('salary', '0006_workingshift_hall_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='cash_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cash_admin', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='hall_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall_admin', to='auth.user'),
        ),
    ]
