# Generated by Django 4.0 on 2021-12-11 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('salary', '0007_workingshift_cash_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingshift',
            name='cash_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_admin', to='auth.user'),
        ),
    ]
