# Generated by Django 4.0.4 on 2022-06-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_remove_profile_confirmation_link_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misconduct',
            name='regulations_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='salary.disciplinaryregulations', verbose_name='Пункт дисциплинарного регламента'),
        ),
    ]
