# Generated by Django 4.0 on 2021-12-12 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='salary.position'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='shortage',
            field=models.FloatField(default=0),
        ),
    ]
