# Generated by Django 4.0.4 on 2022-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_alter_misconduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employment_documents',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Документы о трудоустройстве'),
        ),
    ]
