# Generated by Django 4.0.4 on 2022-06-14 16:19

from django.db import migrations, models

from salary.models import Profile


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_alter_misconduct_status'),
    ]

    def rename_profile_status(*args):
        profiles = Profile.objects.filter(profile_status='ACT')
        for current_profile in profiles:
            current_profile.profile_status = 'VD'
            current_profile.save()

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_status',
            field=models.CharField(choices=[('RG', 'Зарегистрирован'), ('WT', 'Ожидает проверки'), ('VD', 'Проверен'), ('DSM', 'Уволен')], default='RG', max_length=10, verbose_name='Состояние профиля'),
        ),
        migrations.RunPython(rename_profile_status),
    ]
