# Generated by Django 4.0.4 on 2022-08-06 16:27

from django.db import migrations
from django.contrib.auth.models import User, Permission
from salary.models import Profile


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0013_chat_message'),
    ]

    def add_permissions(*args):
        chat_permission = Permission.objects.get(name='Can create new chats')
        for user in User.objects.all():
            if user.profile.profile_status == Profile.ProfileStatus.VERIFIED:
                user.user_permissions.add(chat_permission)
                user.save()

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'permissions': [('can_create_new_chats', 'Can create new chats')], 'verbose_name': 'Chat'},
        ),
        migrations.RunPython(add_permissions),
    ]
