# Generated by Django 4.1 on 2023-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_comment',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
