# Generated by Django 4.0.3 on 2022-04-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingshift',
            old_name='comment',
            new_name='comment_for_cash_admin',
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='comment_for_cash_admin',
            field=models.TextField(blank=True, verbose_name='Примечание для кассира'),
        ),
        migrations.AddField(
            model_name='workingshift',
            name='comment_for_hall_admin',
            field=models.TextField(blank=True, verbose_name='Примечание для админа'),
        ),
    ]
