# Generated by Django 4.1 on 2022-09-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_salary',
            field=models.FloatField(default=0.0),
        ),
    ]
