# Generated by Django 4.1 on 2022-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_rename_vr_revenue'),
    ]

    def set_workshift_status(apps, schema_editor):
        WorkshiftModel = apps.get_model('salary', 'WorkingShift')
        for row in WorkshiftModel.objects.all():
            if row.is_verified:
                row.status = 'VFD'
                row.save()

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='status',
            field=models.CharField(
                choices=[
                    ('UVD', 'Не проверена'),
                    ('WTC', 'Ожидает исправления'),
                    ('VFD', 'Проверена')
                ],
                db_column='shift_status',
                default='UVD',
                max_length=20,
                verbose_name='Статус смены'
            ),
        ),
        migrations.RunPython(set_workshift_status,
                             reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='workingshift',
            name='is_verified',
        ),
    ]
