# Generated by Django 4.1 on 2023-04-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_workingshift_acquiring_evator_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='cost_sum',
            field=models.FloatField(default=0.0, verbose_name='Сумма расходов'),
        ),
        migrations.AlterField(
            model_name='workingshift',
            name='status',
            field=models.CharField(choices=[('NOT_CONFIRMED', 'Не подтверждена'), ('UVD', 'Не проверена'), ('WTC', 'Ожидает исправления'), ('VFD', 'Проверена')], db_column='shift_status', default='NOT_CONFIRMED', max_length=20, verbose_name='Статус смены'),
        ),
    ]
