# Generated by Django 4.1 on 2023-04-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_workingshift_acquiring_evator_sum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время ошибки')),
                ('cabin_number', models.IntegerField(choices=[(1, '№ 1'), (2, '№ 2'), (3, '№ 3'), (4, '№ 4'), (5, '№ 5'), (6, '№ 6')], verbose_name='Номер кабинки')),
                ('description', models.CharField(max_length=255, verbose_name='Причина')),
                ('error_interval', models.CharField(max_length=255, verbose_name='Ошибочное время')),
                ('workshift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin_error', to='salary.workingshift')),
            ],
        ),
    ]
