# Generated by Django 4.1 on 2023-10-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_cabinerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='wishes',
            field=models.TextField(blank=True, verbose_name='Предложения'),
        ),
        migrations.AlterField(
            model_name='cabinerror',
            name='cabin_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Номер кабинки'),
        ),
    ]
