# Generated by Django 4.0.4 on 2022-05-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_profile_email_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmation_link_sent',
            field=models.BooleanField(default=False, verbose_name='Ссылка для подтверждения адреса эл. почты направлена'),
        ),
    ]
