# Generated by Django 4.0.4 on 2022-08-06 20:11

from django.db import migrations, models
from django.contrib.auth.models import User, Permission
from salary.models import Profile


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0014_alter_chat_options'),
    ]

    def add_permissions(*args):
        chat_permission = Permission.objects.get(name='Can create new chats')
        for user in User.objects.all():
            if user.profile.profile_status == Profile.ProfileStatus.VERIFIED:
                user.user_permissions.add(chat_permission)
                user.save()

    operations = [
        migrations.RunPython(add_permissions),
        migrations.AlterField(
            model_name='profile',
            name='profile_status',
            field=models.CharField(choices=[('RG', 'Ожидает разрешение'), ('AU', 'Письмо направлено'), ('WT', 'Ожидает проверки'), ('VD', 'Проверен'), ('DSM', 'Уволен')], default='RG', max_length=10, verbose_name='Состояние профиля'),
        ),
    ]
