# Generated by Django 4.0.3 on 2022-04-24 15:02

from django.db import migrations, models

from salary.models import WorkingShift


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_misconduct_status_misconduct_workshift_date_and_more'),
    ]

    def set_summary_revenue(*args):
        for workshift in WorkingShift.objects.all():
            workshift.save()

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='summary_revenue',
            field=models.FloatField(default=0, verbose_name='Суммарная выручка'),
        ),
        migrations.RunPython(set_summary_revenue),
    ]
