# Generated by Django 4.0.4 on 2022-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0009_alter_misconduct_regulations_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misconduct',
            name='status',
            field=models.CharField(choices=[('AD', 'Ожидает объяснение'), ('WT', 'На рассмотрении'), ('CL', 'Решение принято')], default='AD', max_length=10, verbose_name='Статус рассмотрения'),
        ),
    ]
