# Generated by Django 4.0.4 on 2022-07-10 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import salary.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0012_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='URL')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('sending_time', models.DateTimeField(default=salary.utils.get_current_time, verbose_name='Время отправления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Отметка о прочтении')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='salary.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
    ]
